import type { Prisma } from '../../../../../../node_modules/.prisma/client';
import { z } from 'zod';
import { WHOGrowthStandardOrderByWithRelationInputObjectSchema as WHOGrowthStandardOrderByWithRelationInputObjectSchema } from './objects/WHOGrowthStandardOrderByWithRelationInput.schema';
import { WHOGrowthStandardWhereInputObjectSchema as WHOGrowthStandardWhereInputObjectSchema } from './objects/WHOGrowthStandardWhereInput.schema';
import { WHOGrowthStandardWhereUniqueInputObjectSchema as WHOGrowthStandardWhereUniqueInputObjectSchema } from './objects/WHOGrowthStandardWhereUniqueInput.schema';
import { WHOGrowthStandardCountAggregateInputObjectSchema as WHOGrowthStandardCountAggregateInputObjectSchema } from './objects/WHOGrowthStandardCountAggregateInput.schema';
import { WHOGrowthStandardMinAggregateInputObjectSchema as WHOGrowthStandardMinAggregateInputObjectSchema } from './objects/WHOGrowthStandardMinAggregateInput.schema';
import { WHOGrowthStandardMaxAggregateInputObjectSchema as WHOGrowthStandardMaxAggregateInputObjectSchema } from './objects/WHOGrowthStandardMaxAggregateInput.schema';
import { WHOGrowthStandardAvgAggregateInputObjectSchema as WHOGrowthStandardAvgAggregateInputObjectSchema } from './objects/WHOGrowthStandardAvgAggregateInput.schema';
import { WHOGrowthStandardSumAggregateInputObjectSchema as WHOGrowthStandardSumAggregateInputObjectSchema } from './objects/WHOGrowthStandardSumAggregateInput.schema';

export const WHOGrowthStandardAggregateSchema: z.ZodType<Prisma.WHOGrowthStandardAggregateArgs> = z.object({ orderBy: z.union([WHOGrowthStandardOrderByWithRelationInputObjectSchema, WHOGrowthStandardOrderByWithRelationInputObjectSchema.array()]).optional(), where: WHOGrowthStandardWhereInputObjectSchema.optional(), cursor: WHOGrowthStandardWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), WHOGrowthStandardCountAggregateInputObjectSchema ]).optional(), _min: WHOGrowthStandardMinAggregateInputObjectSchema.optional(), _max: WHOGrowthStandardMaxAggregateInputObjectSchema.optional(), _avg: WHOGrowthStandardAvgAggregateInputObjectSchema.optional(), _sum: WHOGrowthStandardSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.WHOGrowthStandardAggregateArgs>;

export const WHOGrowthStandardAggregateZodSchema = z.object({ orderBy: z.union([WHOGrowthStandardOrderByWithRelationInputObjectSchema, WHOGrowthStandardOrderByWithRelationInputObjectSchema.array()]).optional(), where: WHOGrowthStandardWhereInputObjectSchema.optional(), cursor: WHOGrowthStandardWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), WHOGrowthStandardCountAggregateInputObjectSchema ]).optional(), _min: WHOGrowthStandardMinAggregateInputObjectSchema.optional(), _max: WHOGrowthStandardMaxAggregateInputObjectSchema.optional(), _avg: WHOGrowthStandardAvgAggregateInputObjectSchema.optional(), _sum: WHOGrowthStandardSumAggregateInputObjectSchema.optional() }).strict();