import type { Prisma } from '../../../../../../node_modules/.prisma/client';
import { z } from 'zod';
import { EncounterOrderByWithRelationInputObjectSchema as EncounterOrderByWithRelationInputObjectSchema } from './objects/EncounterOrderByWithRelationInput.schema';
import { EncounterWhereInputObjectSchema as EncounterWhereInputObjectSchema } from './objects/EncounterWhereInput.schema';
import { EncounterWhereUniqueInputObjectSchema as EncounterWhereUniqueInputObjectSchema } from './objects/EncounterWhereUniqueInput.schema';
import { EncounterCountAggregateInputObjectSchema as EncounterCountAggregateInputObjectSchema } from './objects/EncounterCountAggregateInput.schema';
import { EncounterMinAggregateInputObjectSchema as EncounterMinAggregateInputObjectSchema } from './objects/EncounterMinAggregateInput.schema';
import { EncounterMaxAggregateInputObjectSchema as EncounterMaxAggregateInputObjectSchema } from './objects/EncounterMaxAggregateInput.schema';
import { EncounterAvgAggregateInputObjectSchema as EncounterAvgAggregateInputObjectSchema } from './objects/EncounterAvgAggregateInput.schema';
import { EncounterSumAggregateInputObjectSchema as EncounterSumAggregateInputObjectSchema } from './objects/EncounterSumAggregateInput.schema';

export const EncounterAggregateSchema: z.ZodType<Prisma.EncounterAggregateArgs> = z.object({ orderBy: z.union([EncounterOrderByWithRelationInputObjectSchema, EncounterOrderByWithRelationInputObjectSchema.array()]).optional(), where: EncounterWhereInputObjectSchema.optional(), cursor: EncounterWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), EncounterCountAggregateInputObjectSchema ]).optional(), _min: EncounterMinAggregateInputObjectSchema.optional(), _max: EncounterMaxAggregateInputObjectSchema.optional(), _avg: EncounterAvgAggregateInputObjectSchema.optional(), _sum: EncounterSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.EncounterAggregateArgs>;

export const EncounterAggregateZodSchema = z.object({ orderBy: z.union([EncounterOrderByWithRelationInputObjectSchema, EncounterOrderByWithRelationInputObjectSchema.array()]).optional(), where: EncounterWhereInputObjectSchema.optional(), cursor: EncounterWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), EncounterCountAggregateInputObjectSchema ]).optional(), _min: EncounterMinAggregateInputObjectSchema.optional(), _max: EncounterMaxAggregateInputObjectSchema.optional(), _avg: EncounterAvgAggregateInputObjectSchema.optional(), _sum: EncounterSumAggregateInputObjectSchema.optional() }).strict();