import type { Prisma } from '../../../../../../node_modules/.prisma/client';
import { z } from 'zod';
import { WHOGrowthStandardWhereInputObjectSchema as WHOGrowthStandardWhereInputObjectSchema } from './objects/WHOGrowthStandardWhereInput.schema';
import { WHOGrowthStandardOrderByWithAggregationInputObjectSchema as WHOGrowthStandardOrderByWithAggregationInputObjectSchema } from './objects/WHOGrowthStandardOrderByWithAggregationInput.schema';
import { WHOGrowthStandardScalarWhereWithAggregatesInputObjectSchema as WHOGrowthStandardScalarWhereWithAggregatesInputObjectSchema } from './objects/WHOGrowthStandardScalarWhereWithAggregatesInput.schema';
import { WHOGrowthStandardScalarFieldEnumSchema } from './enums/WHOGrowthStandardScalarFieldEnum.schema';
import { WHOGrowthStandardCountAggregateInputObjectSchema as WHOGrowthStandardCountAggregateInputObjectSchema } from './objects/WHOGrowthStandardCountAggregateInput.schema';
import { WHOGrowthStandardMinAggregateInputObjectSchema as WHOGrowthStandardMinAggregateInputObjectSchema } from './objects/WHOGrowthStandardMinAggregateInput.schema';
import { WHOGrowthStandardMaxAggregateInputObjectSchema as WHOGrowthStandardMaxAggregateInputObjectSchema } from './objects/WHOGrowthStandardMaxAggregateInput.schema';
import { WHOGrowthStandardAvgAggregateInputObjectSchema as WHOGrowthStandardAvgAggregateInputObjectSchema } from './objects/WHOGrowthStandardAvgAggregateInput.schema';
import { WHOGrowthStandardSumAggregateInputObjectSchema as WHOGrowthStandardSumAggregateInputObjectSchema } from './objects/WHOGrowthStandardSumAggregateInput.schema';

export const WHOGrowthStandardGroupBySchema: z.ZodType<Prisma.WHOGrowthStandardGroupByArgs> = z.object({ where: WHOGrowthStandardWhereInputObjectSchema.optional(), orderBy: z.union([WHOGrowthStandardOrderByWithAggregationInputObjectSchema, WHOGrowthStandardOrderByWithAggregationInputObjectSchema.array()]).optional(), having: WHOGrowthStandardScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(WHOGrowthStandardScalarFieldEnumSchema), _count: z.union([ z.literal(true), WHOGrowthStandardCountAggregateInputObjectSchema ]).optional(), _min: WHOGrowthStandardMinAggregateInputObjectSchema.optional(), _max: WHOGrowthStandardMaxAggregateInputObjectSchema.optional(), _avg: WHOGrowthStandardAvgAggregateInputObjectSchema.optional(), _sum: WHOGrowthStandardSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.WHOGrowthStandardGroupByArgs>;

export const WHOGrowthStandardGroupByZodSchema = z.object({ where: WHOGrowthStandardWhereInputObjectSchema.optional(), orderBy: z.union([WHOGrowthStandardOrderByWithAggregationInputObjectSchema, WHOGrowthStandardOrderByWithAggregationInputObjectSchema.array()]).optional(), having: WHOGrowthStandardScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(WHOGrowthStandardScalarFieldEnumSchema), _count: z.union([ z.literal(true), WHOGrowthStandardCountAggregateInputObjectSchema ]).optional(), _min: WHOGrowthStandardMinAggregateInputObjectSchema.optional(), _max: WHOGrowthStandardMaxAggregateInputObjectSchema.optional(), _avg: WHOGrowthStandardAvgAggregateInputObjectSchema.optional(), _sum: WHOGrowthStandardSumAggregateInputObjectSchema.optional() }).strict();